/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include "stm32l476xx.h"
#include "stm32l476xx_gpio_driver.h"
#include "stm32l476xx_spi_driver.h"

void delay(uint32_t time) {
    for (uint32_t i = 0; i < time; i++)
        ;
}

// SPI2_SCK PB13
// SPI2_MISO PB14
// SPI2 MOSI PB15
// SPI2 CS PB6

void SPI_GPIO_Setup() {
    // White wire
    GPIO_Handle_t handle = {
        .pGPIOx = GPIOB,
        .GPIO_PinConfig = {
            .GPIO_PinMode = GPIO_MODE_ALTFN,
            .GPIO_PinSpeed = GPIO_SPEED_FAST,
            .GPIO_PinPuPdControl = GPIO_NO_PUPD,
            .GPIO_PinOPType = GPIO_OP_TYPE_PP,
            .GPIO_PinAltFunMode = GPIO_AF_5
        }
    };

    GPIO_PCLK(GPIOB, ENABLE);

    // MOSI
    handle.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_N15;
    GPIO_Init(&handle);

    // SCK
    handle.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_N13;
    GPIO_Init(&handle);

    // MISO
    // handle.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_N14;
    // GPIO_Init(&handle);

    // NSS
    // handle.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_N12;
    // GPIO_Init(&handle);

    // GPIO_WriteToOutputPin(GPIOB, GPIO_PIN_N12, GPIO_PIN_SET);
}

void spi_send() {
    char msg[] = "hello world";

    SPI_GPIO_Setup();

    SPI_Handle_t spi_handle = {
        .pSPIx = SPI2,
        .SPIConfig = {
            .SPI_DeviceMode = SPI_DEVICE_MODE_MASTER,
            .SPI_BusConfig = SPI_BUS_CONFIG_FD, // HD?
            .SPI_SclkSpeed = SPI_SCLK_SPEED_DIV2, // 4 Mhz
            .SPI_DFF = SPI_DFF_8BITS,
            .SPI_CPOL = SPI_CPOL_LOW,
            .SPI_CPHA = SPI_CPAH_LOW,
            .SPI_SSM = SPI_SSM_EN
        }
    };

    SPI_Init(&spi_handle);

    SPI_Enable(spi_handle.pSPIx, ENABLE);

    SPI_SendData(spi_handle.pSPIx, (uint8_t*)msg, strlen(msg));

    // Wait for busy flag to clear
    while(spi_handle.pSPIx->SR & 0x1 << SPI_SR_BSY);

    SPI_Enable(spi_handle.pSPIx, DISABLE);

    while (1) {
    }
}

int main(void) {
    spi_send();
}
